<!DOCTYPE html>
<html>
<head>
    <title>MutPy mutation report - mutation #3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
    
<link href="http://alexgorbatchev.com/pub/sh/current/styles/shCore.css" rel="stylesheet" type="text/css" />
<link href="http://alexgorbatchev.com/pub/sh/current/styles/shThemeDefault.css" rel="stylesheet" type="text/css" />

    <script src="https://code.jquery.com/jquery.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
<script src="http://alexgorbatchev.com/pub/sh/current/scripts/shCore.js" type="text/javascript"></script>
<script src="http://alexgorbatchev.com/pub/sh/current/scripts/shBrushPython.js" type="text/javascript"></script>
<script type="text/javascript">
    SyntaxHighlighter.all();
    window.setTimeout(function () {
        
        $('.line.number13').attr('title', 'COI');
        
    }, 0);
</script>

</head>
<body>
    <div class="container">
        
<div class="page-header">
    <h1>Mutation #3</h1>
</div>
<h3>Details</h3>
<ul>
    <li>module - <code><module 'Ls' from '/workspaces/comp0010psh/src/apps/Ls.py'></code></li>
    <li><span class="label label-success">killed</span> by <code>testLsListDir (testLs.testLs)</code></li>
    
    <li>duration - 0.042 s</li>
    
    
    <li>tests run - 2</li>
    
</ul>

<h3>Exception traceback</h3>
<pre>Traceback (most recent call last):
  File "/workspaces/comp0010psh/test/testLs.py", line 30, in testLsListDir
    self.assertEqual(result1, "test1\ntest2\n")
AssertionError: '.test3\n' != 'test1\ntest2\n'
- .test3
? -    ^
+ test1
?     ^
+ test2


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/comp0010psh/test/testLs.py", line 32, in testLsListDir
    self.fail()
AssertionError: None
</pre>

<h3>Mutations</h3>
<ul>
    
    <li>COI - line 13</li>
    
</ul>
<h3>Mutant</h3>
<pre class="brush: python; first-line: 1; highlight: [13]; toolbar: false;">from apps.Stream import Stream
import os
from apps.Exceptions import InvalidFileOrDir
from apps.decorators import argumentLimit


def listDirectory(ls_dir):
    
    
    dirs = []
    try:
        for file in os.listdir(ls_dir):
            if not ((not (file.startswith('.')))):
                dirs.append(file + '\n')
    except FileNotFoundError:
        raise InvalidFileOrDir('No such file or directory')
    return ''.join(dirs)



@argumentLimit(1, strict=False)
def ls(stream: 'Stream'):args = stream.getArgs()
    stdout = stream.getStdout()
    workingDir = stream.getWorkingDir()
    if len(args) == 0:
        stdout.write(listDirectory(workingDir))
    else:
        stdout.write(listDirectory(args[0]))</pre>

    </div>
</body>
</html>